### PR TITLE
Lock 'zeroize' crate to version 1.3.0

### LINKED ISSUE #9: Braking  the build cargo build --release
error: failed to parse manifest at `/home/aditya/.cargo/registry/src/github.com-1ecc6299db9ec823/zeroize-1.4.1/Cargo.toml`

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest

### PR DESCRIPTION
**Pull request by mbrubeck**
zeroize 1.4.0 and later requires the Cargo 'resolver' feature, which is not available in the nightly-2020-12-16 toolchain.

Fixes #9.

### CODE REVIEW

**Comment by ipopescu** [comment]
@mbrubeck thanks for submitting this. The build is working with your fix. There is a separate issue though with the tests failing. 
Hello world tests

**Comment by mbrubeck** [comment]
> There is a separate issue though with the tests failing.

Pushed a separate commit to fix that.

**Review by ipopescu — APPROVED** [review]
Looks good! Thanks, @mbrubeck!

**Comment by ipopescu** [comment]
Hello world fixed

**Pull request merged**
